name: Eleventy Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ensure packages are installed and usable
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload built site
        uses: actions/upload-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy site to GitHub Pages
        uses: actions/deploy-pages@v2
